# Generated by Django 4.2.4 on 2023-08-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_expenses_amount_alter_orders_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses", name="amount", field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="orders", name="amount", field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="orders", name="quantity", field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="buying_price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="selling_price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="product", name="stock", field=models.PositiveIntegerField(),
        ),
    ]
